DROP TABLE IF EXISTS "AA";
CREATE TABLE "AA" ("ID" INTEGER PRIMARY KEY  NOT NULL , "PortfolioID" INTEGER, "Description" VARCHAR, "Target" NUMERIC);
DROP TABLE IF EXISTS "Acct";
CREATE TABLE "Acct" ("ID" INTEGER PRIMARY KEY  NOT NULL , "PortfolioID" INTEGER, "Description" VARCHAR, "TaxRate" NUMERIC, "TaxDeferred" INTEGER, "CostBasis" INTEGER);
DROP TABLE IF EXISTS "ClosingPrices";
CREATE TABLE "ClosingPrices" ("Date" INTEGER, "Symbol" VARCHAR, "Price" NUMERIC);
DROP TABLE IF EXISTS "Dividends";
CREATE TABLE "Dividends" ("Date" INTEGER, "Symbol" VARCHAR, "Amount" NUMERIC);
DROP TABLE IF EXISTS "ExecutedTrades";
CREATE TABLE "ExecutedTrades" ("SecurityID" INTEGER, "Date" INTEGER, "Shares" NUMERIC, "Price" NUMERIC, 
"Commission" NUMERIC);
DROP TABLE IF EXISTS "NAV";
CREATE TABLE "NAV" ("PortfolioID" INTEGER , "Date" INTEGER, "TotalValue" NUMERIC, "NAV" NUMERIC);
DROP TABLE IF EXISTS "Portfolios";
CREATE TABLE "Portfolios" ("ID" INTEGER PRIMARY KEY  NOT NULL , "Description" VARCHAR, "StartValue" INTEGER, "AAThreshold" INTEGER, "ThresholdMethod" INTEGER, "CostBasis" INTEGER, "StartDate" INTEGER, "Dividends" INTEGER, "HoldingsShowHidden" INTEGER, "HoldingsSort" VARCHAR, "AAShowBlank" INTEGER, "AASort" VARCHAR, "CorrelationShowHidden" INTEGER, "AcctShowBlank" INTEGER, "AcctSort" VARCHAR, "NAVSortDesc" INTEGER);
DROP TABLE IF EXISTS "Security";
CREATE TABLE "Security" ("ID" INTEGER PRIMARY KEY  NOT NULL ,"PortfolioID" INTEGER,"Symbol" VARCHAR,"Account" INTEGER,"Expense" DOUBLE,"DivReinvest" INTEGER,"CashAccount" INTEGER,"IncludeInCalc" INTEGER,"Hide" INTEGER);
DROP TABLE IF EXISTS "SecurityAA";
CREATE TABLE "SecurityAA" ("SecurityID" INTEGER, "AAID" INTEGER, "Percent" NUMERIC);
DROP TABLE IF EXISTS "SecurityTrades";
CREATE TABLE "SecurityTrades" ("ID" INTEGER PRIMARY KEY  NOT NULL , "SecurityID" INTEGER, "Type" INTEGER, "Value" NUMERIC, "Price" NUMERIC, "Commission" NUMERIC, "CashAccountID" INTEGER, "Frequency" INTEGER, "Date" INTEGER, "StartDate" INTEGER, "EndDate" INTEGER);
DROP TABLE IF EXISTS "Settings";
CREATE TABLE "Settings" ("DataStartDate" INTEGER,"LastPortfolio" INTEGER,"Version" INTEGER,"WindowX" INTEGER,"WindowY" INTEGER,"WindowHeight" INTEGER,"WindowWidth" INTEGER,"WindowState" INTEGER,"Splits" INTEGER,"CompareIncludeDividends" INTEGER);
INSERT INTO "Settings" VALUES(2454468,NULL,300,NULL,NULL,NULL,NULL,NULL,1,1);
DROP TABLE IF EXISTS "SettingsColumns";
CREATE TABLE "SettingsColumns" ("ID" INTEGER, "ColumnID" INTEGER, "Sequence" INTEGER);
INSERT INTO "SettingsColumns" VALUES(0,0,0);
INSERT INTO "SettingsColumns" VALUES(0,1,1);
INSERT INTO "SettingsColumns" VALUES(0,2,2);
INSERT INTO "SettingsColumns" VALUES(0,3,3);
INSERT INTO "SettingsColumns" VALUES(0,4,4);
INSERT INTO "SettingsColumns" VALUES(0,5,5);
INSERT INTO "SettingsColumns" VALUES(0,6,6);
INSERT INTO "SettingsColumns" VALUES(0,7,7);
INSERT INTO "SettingsColumns" VALUES(0,8,8);
INSERT INTO "SettingsColumns" VALUES(0,9,9);
INSERT INTO "SettingsColumns" VALUES(0,10,10);
INSERT INTO "SettingsColumns" VALUES(0,11,11);
INSERT INTO "SettingsColumns" VALUES(0,12,12);
INSERT INTO "SettingsColumns" VALUES(0,13,13);
INSERT INTO "SettingsColumns" VALUES(0,14,14);
INSERT INTO "SettingsColumns" VALUES(2,0,0);
INSERT INTO "SettingsColumns" VALUES(2,1,1);
INSERT INTO "SettingsColumns" VALUES(2,2,2);
INSERT INTO "SettingsColumns" VALUES(2,3,3);
INSERT INTO "SettingsColumns" VALUES(2,4,4);
INSERT INTO "SettingsColumns" VALUES(2,5,5);
INSERT INTO "SettingsColumns" VALUES(2,6,6);
INSERT INTO "SettingsColumns" VALUES(2,7,7);
INSERT INTO "SettingsColumns" VALUES(2,8,8);
INSERT INTO "SettingsColumns" VALUES(2,9,9);
INSERT INTO "SettingsColumns" VALUES(1,0,0);
INSERT INTO "SettingsColumns" VALUES(1,1,1);
INSERT INTO "SettingsColumns" VALUES(1,2,2);
INSERT INTO "SettingsColumns" VALUES(1,3,3);
INSERT INTO "SettingsColumns" VALUES(1,4,4);
INSERT INTO "SettingsColumns" VALUES(1,5,5);
INSERT INTO "SettingsColumns" VALUES(1,6,6);
INSERT INTO "SettingsColumns" VALUES(1,7,7);
INSERT INTO "SettingsColumns" VALUES(1,8,8);
INSERT INTO "SettingsColumns" VALUES(1,9,9);
DROP TABLE IF EXISTS "Splits";
CREATE TABLE "Splits" ("Date" INTEGER, "Symbol" VARCHAR, "Ratio" NUMERIC);
DROP TABLE IF EXISTS "StatMapping";
CREATE TABLE "StatMapping" ("PortfolioID" INTEGER, "StatID" INTEGER, "Sequence" INTEGER);
